---
x-pg-host: &pghost huautla
x-pg-port: &pgport 5432
x-pg-user: &pguser postgres
x-pg-pass: &pgpass root
x-pg-ssl: &pgssl disable

services:
  postgres:
    image: huautla:latest
    build: .
    restart: always
    hostname: huautla
    ports:
      - 5434:5432
    volumes: [ .:/huautla ]
    environment:
      POSTGRES_PASSWORD: *pgpass

  system-test:
    depends_on: [ postgres ]
    image: golang:bookworm
    volumes: [ .:/go/src/github.com/jsmit257/huautla ]
    environment:
      POSTGRES_HOST: *pghost
      POSTGRES_PORT: *pgport
      POSTGRES_USER: *pguser
      POSTGRES_PASSWORD: *pgpass
      POSTGRES_SSLMODE: *pgssl
    working_dir: /go/src/github.com/jsmit257/huautla
    command: ./bin/system-test.sh
