---
version: "3.1"

x-pg-host: &pghost huautla
x-pg-port: &pgport 5432
x-pg-user: &pguser postgres
x-pg-pass: &pgpass root

services:

  postgres:
    image: postgres:bookworm
    restart: always
    hostname: huautla
    # volumes: [ .:/go/src/build ]
    ports:
      - 5433:5432
    environment:
      POSTGRES_PASSWORD: *pgpass

  initdb:
    depends_on: [ postgres ]
    image: initdb # debian:bookworm
    # volumes: [ .:/root/huautla ]
    environment:
      POSTGRES_HOST: *pghost
      POSTGRES_PORT: *pgport
      POSTGRES_USER: *pguser
      POSTGRES_PASSWORD: *pgpass
    # working_dir: /root/huautla
    # command: ./bin/schema.sh

  system-test:
    depends_on: [ initdb ]
    image: system-test
    environment:
      POSTGRES_HOST: *pghost
      POSTGRES_PORT: *pgport
      POSTGRES_USER: *pguser
      POSTGRES_PASSWORD: *pgpass
